<?php

include_once('objective_planning.features.inc');

/**
 * Implementation of hook_init().
 */
function objective_planning_init() {
  $path = drupal_get_path('module', 'objective_planning') ;
  drupal_add_css($path . '/css/objective_planning.css'); 	
//die(print_r($path . '/css/objective_planning.css'));
  //drupal_add_js(drupal_get_path('module', 'objective_planning') . '/js/objective_planning.js');
 }
