<?php
/**
 * @file
 * game_war.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function game_war_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-set_ri-field_atacuri_primite_2'.
  $field_instances['node-set_ri-field_atacuri_primite_2'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 10,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_atacuri_primite_2',
    'label' => 'Atacuri primite la fiecare 15 min (bonus 1)',
    'required' => 1,
    'settings' => array(
      'max' => 50,
      'min' => 2,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_atacuri_primite_3'.
  $field_instances['node-set_ri-field_atacuri_primite_3'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 20,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_atacuri_primite_3',
    'label' => 'Atacuri primite la fiecare 15 min (bonus 2)',
    'required' => 1,
    'settings' => array(
      'max' => 50,
      'min' => 2,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_atacuri_primite_la_fiecare'.
  $field_instances['node-set_ri-field_atacuri_primite_la_fiecare'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 3,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_atacuri_primite_la_fiecare',
    'label' => 'Atacuri primite la fiecare 15 min',
    'required' => 1,
    'settings' => array(
      'max' => 15,
      'min' => 1,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_la_fiecare_15_min_pt_fieca'.
  $field_instances['node-set_ri-field_la_fiecare_15_min_pt_fieca'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 4,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 10,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_la_fiecare_15_min_pt_fieca',
    'label' => 'La fiecare 15 min, pt. fiecare soldat se primesc',
    'required' => 1,
    'settings' => array(
      'max' => 15,
      'min' => 1,
      'prefix' => '',
      'suffix' => 'bani',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_la_fiecare_nivel_aparare_p'.
  $field_instances['node-set_ri-field_la_fiecare_nivel_aparare_p'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 10,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_la_fiecare_nivel_aparare_p',
    'label' => 'La fiecare nivel aparare, pret arme aparare creste cu',
    'required' => 1,
    'settings' => array(
      'max' => 50,
      'min' => 2,
      'prefix' => '',
      'suffix' => '%',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_la_fiecare_nivel_atac_pret'.
  $field_instances['node-set_ri-field_la_fiecare_nivel_atac_pret'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 10,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_la_fiecare_nivel_atac_pret',
    'label' => 'La fiecare nivel atac, pret arme creste cu',
    'required' => 1,
    'settings' => array(
      'max' => 50,
      'min' => 2,
      'prefix' => '',
      'suffix' => '%',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_nivel_aparare_creste_la_fi'.
  $field_instances['node-set_ri-field_nivel_aparare_creste_la_fi'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 5000,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_nivel_aparare_creste_la_fi',
    'label' => 'Nivel aparare creste la fiecare',
    'required' => 1,
    'settings' => array(
      'max' => 10000,
      'min' => 100,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_nivel_atac_creste_la_fieca'.
  $field_instances['node-set_ri-field_nivel_atac_creste_la_fieca'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 5000,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_nivel_atac_creste_la_fieca',
    'label' => 'Nivel atac creste la fiecare',
    'required' => 1,
    'settings' => array(
      'max' => 10000,
      'min' => 100,
      'prefix' => '',
      'suffix' => 'bonus',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_nr_maxim_atacuri'.
  $field_instances['node-set_ri-field_nr_maxim_atacuri'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 700,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_nr_maxim_atacuri',
    'label' => 'Nr. maxim atacuri (fara bonus)',
    'required' => 1,
    'settings' => array(
      'max' => 3000,
      'min' => 300,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_nr_maxim_atacuri_bonus_1_'.
  $field_instances['node-set_ri-field_nr_maxim_atacuri_bonus_1_'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 1000,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_nr_maxim_atacuri_bonus_1_',
    'label' => 'Nr. maxim atacuri (bonus 1)',
    'required' => 1,
    'settings' => array(
      'max' => 3000,
      'min' => 300,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_nr_maxim_atacuri_bonus_2_'.
  $field_instances['node-set_ri-field_nr_maxim_atacuri_bonus_2_'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 1300,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_nr_maxim_atacuri_bonus_2_',
    'label' => 'Nr. maxim atacuri (bonus 2)',
    'required' => 1,
    'settings' => array(
      'max' => 3000,
      'min' => 300,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 10,
    ),
  );

  // Exported field_instance: 'node-set_ri-field_nr_maxim_depuneri_seif_pe_'.
  $field_instances['node-set_ri-field_nr_maxim_depuneri_seif_pe_'] = array(
    'bundle' => 'set_ri',
    'default_value' => array(
      0 => array(
        'value' => 14,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 11,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_nr_maxim_depuneri_seif_pe_',
    'label' => 'Nr. maxim depuneri seif pe sapt',
    'required' => 1,
    'settings' => array(
      'max' => 70,
      'min' => 7,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'profile2-garnizoan_-field_strategie'.
  $field_instances['profile2-garnizoan_-field_strategie'] = array(
    'bundle' => 'garnizoan_',
    'default_value' => array(
      0 => array(
        'value' => 3,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'profile2',
    'field_name' => 'field_strategie',
    'label' => 'Strategie',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'profile2-main-field_adresa'.
  $field_instances['profile2-main-field_adresa'] = array(
    'bundle' => 'main',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'profile2',
    'field_name' => 'field_adresa',
    'label' => 'Adresa',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'profile2-main-field_caracter'.
  $field_instances['profile2-main-field_caracter'] = array(
    'bundle' => 'main',
    'default_value' => array(
      0 => array(
        'value' => 1,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'profile2',
    'field_name' => 'field_caracter',
    'label' => 'Caracter',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'profile2-main-field_despre'.
  $field_instances['profile2-main-field_despre'] = array(
    'bundle' => 'main',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'profile2',
    'field_name' => 'field_despre',
    'label' => 'Despre',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'profile2-main-field_localitate'.
  $field_instances['profile2-main-field_localitate'] = array(
    'bundle' => 'main',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'profile2',
    'field_name' => 'field_localitate',
    'label' => 'Localitate',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 40,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'profile2-main-field_nume'.
  $field_instances['profile2-main-field_nume'] = array(
    'bundle' => 'main',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'profile2',
    'field_name' => 'field_nume',
    'label' => 'Nume',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 35,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'profile2-main-field_prenume'.
  $field_instances['profile2-main-field_prenume'] = array(
    'bundle' => 'main',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'profile2',
    'field_name' => 'field_prenume',
    'label' => 'Prenume',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Adresa');
  t('Atacuri primite la fiecare 15 min');
  t('Atacuri primite la fiecare 15 min (bonus 1)');
  t('Atacuri primite la fiecare 15 min (bonus 2)');
  t('Caracter');
  t('Despre');
  t('La fiecare 15 min, pt. fiecare soldat se primesc');
  t('La fiecare nivel aparare, pret arme aparare creste cu');
  t('La fiecare nivel atac, pret arme creste cu');
  t('Localitate');
  t('Nivel aparare creste la fiecare');
  t('Nivel atac creste la fiecare');
  t('Nr. maxim atacuri (bonus 1)');
  t('Nr. maxim atacuri (bonus 2)');
  t('Nr. maxim atacuri (fara bonus)');
  t('Nr. maxim depuneri seif pe sapt');
  t('Nume');
  t('Prenume');
  t('Strategie');

  return $field_instances;
}
